AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  pGitHubToken:
    Type: String
    Description: GitHub Token
  pGitHubOwner:
    Type: String
    Description: GitHub Owner
    Default: iacobucci
  pGitHubRepo:
    Type: String
    Description: GitHub Repo
    Default: express-aws
  pGitHubBranch:
    Type: String
    Description: GitHub Branch
    Default: ecs
  pEnvironmentName:
    Type: String
    Description: Nome dell'ambiente
    Default: valerio-env
  

Resources:
    Cluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: !Ref pEnvironmentName

    Service:
        Type: AWS::ECS::Service
        Properties:
            Cluster: !Ref Cluster
            LaunchType: FARGATE
            DesiredCount: 2
            DeploymentConfiguration:
                MaximumPercent: 150
                MinimumHealthyPercent: 100
            TaskDefinition: !Ref TaskDefinition
            NetworkConfiguration:
                AwsvpcConfiguration:
                    Subnets:
                      - Fn::ImportValue: valerio-privatesubnet1
                      - Fn::ImportValue: valerio-privatesubnet2
                      - Fn::ImportValue: valerio-publicsubnet1
                      - Fn::ImportValue: valerio-publicsubnet2
                    AssignPublicIp: ENABLED
                    SecurityGroups:
                        - Fn::ImportValue: valerio-securitygroup
            LoadBalancers:
                - ContainerName: !Ref pEnvironmentName
                  ContainerPort: 3000
                  TargetGroupArn: !ImportValue valerio-fargatetargetgroup

    TaskExecutionRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                - Effect: Allow
                  Principal:
                      Service:
                      - ecs-tasks.amazonaws.com
                  Action:
                  - sts:AssumeRole
            ManagedPolicyArns:
                - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            TaskRoleArn: !GetAtt TaskExecutionRole.Arn
            ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
            Cpu: 256
            Memory: 512
            Family: !Ref pEnvironmentName
            NetworkMode: awsvpc
            RequiresCompatibilities:
                - FARGATE
            ContainerDefinitions:
                - Name: !Ref pEnvironmentName
                  Environment:
                      - Name : S3_BUCKET
                        Value: "valerio-bucket-s3"
                      - Name: RDS_USERNAME
                        Value: "admin"
                      - Name: RDS_PASSWORD
                        Value: "password"
                      - Name: RDS_HOSTNAME
                        Value: "127.0.0.1"
                      - Name: RDS_PORT
                        Value: "3306"
                      - Name: RDS_DATABASE
                        Value: "node"
                  PortMappings:
                      - ContainerPort: 3000
                  Image: docker.io/laser/helloworld-http:latest
                  LogConfiguration:
                      LogDriver: awslogs
                      Options:
                          awslogs-group: !Ref pEnvironmentName
                          awslogs-region: !Ref AWS::Region
                          awslogs-stream-prefix: ecs

    LogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Ref pEnvironmentName
            RetentionInDays: 365