AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template per il deployment della pipeline ECS con Fargate

Parameters:
  ## passabile con --parameters
  # pGitHubToken:
  #   Type: String
  #   Description: GitHub Token
  pGitHubOwner:
    Type: String
    Description: GitHub Owner
    Default: iacobucci
  pGitHubRepo:
    Type: String
    Description: GitHub Repo
    Default: express-aws
  pGitHubBranch:
    Type: String
    Description: GitHub Branch
    Default: ecs
  pCodeStarConnectionArn:
    Type: String
    Description: GitHub Connection ARN for the repository
    Default: arn:aws:codestar-connections:eu-north-1:861507897222:connection/e1c42544-481c-47df-aa9e-0ef7ea5e2f09
  pEnvironmentName:
    Type: String
    Description: Nome dell'ambiente
    Default: valerio-env
  pEnvironmentTag:
    Type: String
    Description: Tag dell'ambiente
    Default: valerio-env

Resources:
  
  CodeStarConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties: 
      ConnectionName: String
      HostArn: String
      ProviderType: String
        
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-artifacts
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 1
            NoncurrentVersionExpirationInDays: 1
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
                
  EcrRepository:
    Type: AWS::ECR::Repository


  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-project
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/codeBuildServiceRole
      VpcConfig:
        VpcId:
          valerio-vpc
        Subnets:
          - Fn::ImportValue: valerio-privatesubnet1
          - Fn::ImportValue: valerio-privatesubnet2
        SecurityGroupIds:
          - Fn::ImportValue: valerio-securitygroup
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
          - Name: REPOSITORY_URI
            Type: PLAINTEXT
            Value: !GetAtt EcrRepository.RepositoryUri
          - Name: ECR_ENDPOINT
            Type: PLAINTEXT
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          - Name: ENVIRONMENT
            Type: PLAINTEXT
            Value: !Ref pEnvironmentTag
          - Name: APP_NAME
            Type: PLAINTEXT
            Value: !Ref AWS::StackName
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
          - LOCAL_DOCKER_LAYER_CACHE

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: valerio-pipeline
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/CodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceCodeStar
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: '1'
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: Source
              Configuration:
                ConnectionArn: !Ref pCodeStarConnectionArn
                BranchName: !Ref pGitHubBranch
                FullRepositoryId: !Sub ${pGitHubOwner}/${pGitHubRepo}
                OutputArtifactFormat: CODEBUILD_CLONE_REF
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: Source
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: ECS
              Configuration:
                ClusterName:
                  - Fn::ImportValue: valerio-cluster
                ServiceName: 
                  - Fn::ImportValue: valerio-service
                FileName: images.json
              InputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
                    
Outputs:
  CodeBuildProject:
    Description: CodeBuild Project
    Value: !Ref CodeBuildProject
    Export:
      Name: valerio-codebuildproject
  Pipeline:
    Description: CodePipeline
    Value: !Ref Pipeline
    Export:
      Name: valerio-pipeline
  CodesStarConnection:
    Description: CodeStar Connection
    Value: !Ref CodeStarConnection
    Export:
      Name: valerio-codestarconnection
  ArtifactBucket:
    Description: Artifact Bucket
    Value: !Ref ArtifactBucket
    Export:
      Name: valerio-artifactbucket
  EcrRepository:
    Description: ECR Repository
    Value: !Ref EcrRepository
    Export:
      Name: valerio-ecrrepository
      