AWSTemplateFormatVersion: '2010-09-09'
Description: Creazione di una VPC con 4 subnet (2 private e 2 pubbliche), Route Tables in eu-north-1a e eu-north-1b.

Resources:
  # Crere Vpc
  ValerioVpcCfn:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.56.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: valerio-vpc-cf

  # Creare due subnet pubbliche
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'eu-north-1a'
      VpcId: !Ref ValerioVpcCfn
      CidrBlock: '10.56.5.0/24'
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'eu-north-1b'
      VpcId: !Ref ValerioVpcCfn
      CidrBlock: '10.56.6.0/24'
      MapPublicIpOnLaunch: true

  # Creare due subnet private
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'eu-north-1a'
      VpcId: !Ref ValerioVpcCfn
      CidrBlock: '10.56.15.0/24'
      MapPublicIpOnLaunch: false

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'eu-north-1b'
      VpcId: !Ref ValerioVpcCfn
      CidrBlock: '10.56.16.0/24'
      MapPublicIpOnLaunch: false

  # Creare una Route Table pubblica
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ValerioVpcCfn
      Tags:
        - Key: Name
          Value: PublicRouteTable

  # Creare una Route Table privata
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ValerioVpcCfn
      Tags:
        - Key: Name
          Value: PrivateRouteTable

  # Associare le subnet pubbliche alla Route Table pubblica
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  # Associare le subnet private alla Route Table privata
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable
